# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/vivo/extract-files.sh - DO NOT EDIT

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \
    vendor/htc/vivo/proprietary/libcamera.so:obj/lib/libcamera.so \
    vendor/htc/vivo/proprietary/libaudioalsa.so:obj/lib/libaudioalsa.so 

# Added from existz aospx, prebuilt v8 libs
PRODUCT_COPY_FILES += \
    vendor/htc/vivo/proprietary/libv8.so:obj/lib/libv8.so \
    vendor/htc/vivo/proprietary/libv8.so:system/lib/libv8.so

# All the blobs necessary for vivo
PRODUCT_COPY_FILES += \
    vendor/htc/vivo/proprietary/akmd:/system/bin/akmd \
    vendor/htc/vivo/proprietary/bma150_usr:/system/bin/bma150_usr \
    vendor/htc/vivo/proprietary/htc_ebdlogd:/system/bin/htc_ebdlogd \
    vendor/htc/vivo/proprietary/logcat2:/system/bin/logcat2 \
    vendor/htc/vivo/proprietary/rmt_storage:/system/bin/rmt_storage \
    vendor/htc/vivo/proprietary/snd3254:/system/bin/snd3254 \
    vendor/htc/vivo/proprietary/AudioBTID.csv:/system/etc/AudioBTID.csv \
    vendor/htc/vivo/proprietary/eglsubAndroid.so:/system/lib/egl/eglsubAndroid.so \
    vendor/htc/vivo/proprietary/libEGL_adreno200.so:/system/lib/egl/libEGL_adreno200.so \
    vendor/htc/vivo/proprietary/libGLES_android.so:/system/lib/egl/libGLES_android.so \
    vendor/htc/vivo/proprietary/libGLESv1_CM_adreno200.so:/system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/htc/vivo/proprietary/libGLESv2_adreno200.so:/system/lib/egl/libGLESv2_adreno200.so \
    vendor/htc/vivo/proprietary/libq3dtools_adreno200.so:/system/lib/egl/libq3dtools_adreno200.so \
    vendor/htc/vivo/proprietary/libgsl.so:/system/lib/libgsl.so \
    vendor/htc/vivo/proprietary/libsc-a2xx.so:/system/lib/libsc-a2xx.so \
    vendor/htc/vivo/proprietary/libC2D2.so:/system/lib/libC2D2.so \
    vendor/htc/vivo/proprietary/libOpenVG.so:/system/lib/libOpenVG.so \
    vendor/htc/vivo/proprietary/libaudioalsa.so:/system/lib/libaudioalsa.so \
    vendor/htc/vivo/proprietary/libgemini.so:/system/lib/libgemini.so \
    vendor/htc/vivo/proprietary/libhtc_acoustic.so:/system/lib/libhtc_acoustic.so \
    vendor/htc/vivo/proprietary/libhtc_ril.so:/system/lib/libhtc_ril.so \
    vendor/htc/vivo/proprietary/libmmipl.so:/system/lib/libmmipl.so \
    vendor/htc/vivo/proprietary/libmmjpeg.so:/system/lib/libmmjpeg.so \
    vendor/htc/vivo/proprietary/libcamera.so:/system/lib/libcamera.so \
    vendor/htc/vivo/proprietary/libcamera.so:/obj/lib/libcamera.so \
    vendor/htc/vivo/proprietary/lsc_camera:/system/bin/lsc_camera \
    vendor/htc/vivo/proprietary/liboemcamera.so:/system/lib/liboemcamera.so \
    vendor/htc/vivo/proprietary/awb_camera:/system/bin/awb_camera \
    vendor/htc/vivo/proprietary/gps.vivo.so:/system/lib/hw/gps.vivo.so

# Added from LorD ClockaN IceColdSandwich
PRODUCT_COPY_FILES += \
    vendor/htc/vivo/apps/wifixmanager.apk:/system/app/wifixmanager.apk \
    vendor/htc/vivo/apps/modelid_cfg.sh:/system/bin/modelid_cfg.sh \
    vendor/htc/vivo/apps/audio_effects.conf:/system/etc/audio_effects.conf \
    vendor/htc/vivo/apps/GooManager_1.5.3_signed.apk:/system/app/GooManager.apk \
    vendor/htc/vivo/apps/ApexLauncher_v1.0.2.apk:/system/app/ApexLauncher.apk

# Facelock Libraries
PRODUCT_COPY_FILES += \
    vendor/kaijura/google/libfacelock_jni.so:system/lib/libfacelock_jni.so \
    vendor/kaijura/google/libfilterpack_facedetect.so:system/lib/libfilterpack_facedetect.so

# Facelock App
PRODUCT_COPY_FILES += \
    vendor/kaijura/google/FaceLock.apk:system/app/FaceLock.apk

# Facelock vendor files
PRODUCT_COPY_FILES += \
    vendor/kaijura/google/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.3/left_eye-y0-yi45-p0-pi45-r0-ri20.2d_n2/full_model.bin:system/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.3/left_eye-y0-yi45-p0-pi45-r0-ri20.2d_n2/full_model.bin \
    vendor/kaijura/google/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.3/left_eye-y0-yi45-p0-pi45-rn7-ri20.2d_n2/full_model.bin:system/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.3/left_eye-y0-yi45-p0-pi45-rn7-ri20.2d_n2/full_model.bin \
    vendor/kaijura/google/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.3/left_eye-y0-yi45-p0-pi45-rp7-ri20.2d_n2/full_model.bin:system/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.3/left_eye-y0-yi45-p0-pi45-rp7-ri20.2d_n2/full_model.bin \
    vendor/kaijura/google/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.3/nose_base-y0-yi45-p0-pi45-r0-ri20.2d_n2/full_model.bin:system/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.3/nose_base-y0-yi45-p0-pi45-r0-ri20.2d_n2/full_model.bin \
    vendor/kaijura/google/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.3/nose_base-y0-yi45-p0-pi45-rn7-ri20.2d_n2/full_model.bin:system/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.3/nose_base-y0-yi45-p0-pi45-rn7-ri20.2d_n2/full_model.bin \
    vendor/kaijura/google/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.3/nose_base-y0-yi45-p0-pi45-rp7-ri20.2d_n2/full_model.bin:system/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.3/nose_base-y0-yi45-p0-pi45-rp7-ri20.2d_n2/full_model.bin \
    vendor/kaijura/google/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.3/right_eye-y0-yi45-p0-pi45-r0-ri20.2d_n2/full_model.bin:system/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.3/right_eye-y0-yi45-p0-pi45-r0-ri20.2d_n2/full_model.bin \
    vendor/kaijura/google/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.3/right_eye-y0-yi45-p0-pi45-rn7-ri20.2d_n2/full_model.bin:system/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.3/right_eye-y0-yi45-p0-pi45-rn7-ri20.2d_n2/full_model.bin \
    vendor/kaijura/google/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.3/right_eye-y0-yi45-p0-pi45-rp7-ri20.2d_n2/full_model.bin:system/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.3/right_eye-y0-yi45-p0-pi45-rp7-ri20.2d_n2/full_model.bin \
    vendor/kaijura/google/vendor/pittpatt/models/detection/yaw_roll_face_detectors.3/head-y0-yi45-p0-pi45-r0-ri30.4a/full_model.bin:system/vendor/pittpatt/models/detection/yaw_roll_face_detectors.3/head-y0-yi45-p0-pi45-r0-ri30.4a/full_model.bin \
    vendor/kaijura/google/vendor/pittpatt/models/detection/yaw_roll_face_detectors.3/head-y0-yi45-p0-pi45-rn30-ri30.5/full_model.bin:system/vendor/pittpatt/models/detection/yaw_roll_face_detectors.3/head-y0-yi45-p0-pi45-rn30-ri30.5/full_model.bin \
    vendor/kaijura/google/vendor/pittpatt/models/detection/yaw_roll_face_detectors.3/head-y0-yi45-p0-pi45-rp30-ri30.5/full_model.bin:system/vendor/pittpatt/models/detection/yaw_roll_face_detectors.3/head-y0-yi45-p0-pi45-rp30-ri30.5/full_model.bin \
    vendor/kaijura/google/vendor/pittpatt/models/recognition/face.face.y0-y0-22-b-N/full_model.bin:system/vendor/pittpatt/models/recognition/face.face.y0-y0-22-b-N/full_model.bin

# Rotating softkeys by st.matt
# Patched libsurfaceflinger Not needed for 4.3+, now working in default surfaceflinger source
#PRODUCT_COPY_FILES += \
#    vendor/htc/vivo/proprietary/libsurfaceflinger.so:/system/lib/libsurfaceflinger.so
